#! /bin/sh
### BEGIN INIT INFO
# Provides: ipset-pre
# Required-Start:    $local_fs $syslog 
# Required-Stop:     $local_fs $syslog $remote_fs
# X-Start-Before:    netfilter-persistent iptables-persistent netfilter iptables
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: configure firewall ipsets
### END INIT INFO
#
# ipset    firewall ipsets subsystem starting and stopping
#
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC=ipset-pre

FWSET=/usr/local/src/ipset-blacklist/v4-blacklist.sh
IPSET=/sbin/ipset

test -f $FWSET || exit 0
test -f $IPSET || exit 0

test -f /etc/default/rcS && . /etc/default/rcS

. /lib/lsb/init-functions

set -e

case $1 in
  start)
	log_daemon_msg "Starting $DESC"

	start-stop-daemon --start --name ipsets --oknodo --exec ${FWSET} -- sets
	log_progress_msg "${FWSET##*/}"

	log_end_msg 0
  ;;
  stop)
	log_daemon_msg "Stopping $DESC"

	start-stop-daemon --stop --name ipsets --oknodo --exec ${FWSET} -- sets
	log_progress_msg "${FWSET##*/}"

	log_end_msg 0
  ;;
  restart|force-reload)
	$0 stop
	sleep 1
	$0 start
  ;;
  *)
	N=/etc/init.d/${DESC}
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

# vim:noet
